//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 15/10/2022 20:48:47
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Reflection;
using System.Linq.Expressions;
using System.Data.Entity.Core;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata


#endregion

namespace AceitaspixModel
{

    #region AceitaspixEntities

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AceitaspixEntities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initialize a new AceitaspixEntities object.
        /// </summary>
        public AceitaspixEntities() :
                base(@"name=AceitaspixEntitiesConnectionString", "AceitaspixEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initializes a new AceitaspixEntities object using the connection string found in the 'AceitaspixEntities' section of the application configuration file.
        /// </summary>
        public AceitaspixEntities(string connectionString) :
                base(connectionString, "AceitaspixEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new AceitaspixEntities object.
        /// </summary>
        public AceitaspixEntities(EntityConnection connection) : base(connection, "AceitaspixEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }


        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        #endregion
        #region AddTo Methods

        #endregion
    }

    #endregion
}
